name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # PR時だけロールと変更範囲を検査
  gate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read labels
        id: labels
        run: |
          echo "labels=${{ join(github.event.pull_request.labels.*.name, ',') }}" >> $GITHUB_OUTPUT

      - name: Changed files (vs base)
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff --name-only origin/${{ github.base_ref }}...HEAD > changed.txt || true
          echo "Changed files:"; cat changed.txt || true

      - name: Enforce role policy
        run: |
          labels="${{ steps.labels.outputs.labels }}"
          echo "Labels: $labels"
          if [[ "$labels" != *"role:coder"* && "$labels" != *"role:tester"* ]]; then
            echo "❌ 必要ラベルがありません（role:coder か role:tester を付与してください）"; exit 1; fi
          if [[ "$labels" == *"role:coder"* ]]; then
            if grep -E '^tests/' changed.txt; then
              echo "❌ coder PR は tests/ を変更できません"; exit 1; fi
          fi
          if [[ "$labels" == *"role:tester"* ]]; then
            if grep -vE '^(tests/|AGENT.md$|README.md$|.github/|requirements.*)$' changed.txt | grep .; then
              echo "❌ tester PR は tests/ とドキュメント以外を変更できません"; exit 1; fi
          fi

  # PR時のテスト（gate通過が前提）
  test_pr:
    if: github.event_name == 'pull_request'
    needs: [gate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run tests
        run: pytest -q

  # push時のテスト（従来どおり）
  test_push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run tests
        run: pytest -q
